In [7]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [41]:
import pandas as pd
from pathlib import Path

file_path = Path(r"C:\laragon\www\web\lokalkita\data\metadata.xlsx")

df = pd.read_excel(file_path)
df.head()

,item_id,title,description,tags,category,location,state,min price (RM),max price (RM),operating hours,operating days,closing days,rating,host_id,host_name,contact,more_info
0,1,Ilham Ceramic Studio,"Ilham Seramik Studio showcases ceramic-making,...","ceramic, crafts, pottery",Arts & Crafts,"Ilham Ceramic Studio, Kampung Bendang Baru, 07...",Kedah,8.0,518.0,9 am - 5 pm,Daily,Friday,4.8,HO1,Radzi Ismail,013-599 4022,https://www.instagram.com/ilham_ceramic/?hl=en
1,2,Maklang Cafe by Ilham Ceramic Studio,Maklang Cafe by Ilham Ceramic offers cultural ...,"food, culture, culinary",Food & Culinary,"Ilham Ceramic Studio, Kampung Bendang Baru, 07...",Kedah,0.5,15.0,8 am - 6 pm,Daily,Friday,4.8,HO1,Radzi Ismail,013-599 4022,https://naturallylangkawi.my/portfolio/ilham-s...
2,3,Perencah Mee Bandung Mak Pon,Perencah Mee Bandung Mak Pon offers varieties ...,"food, paste, culinary",Food & Culinary,"1, 2 & 3, Jalan Lembah Padang, Taman Lembah Pa...",Johor,12.0,30.0,10 am - 7 pm,Daily,NaN,4.0,HO2,JJ Makpon Muar,012-262 0044,https://shopee.com.my/Pes-Mee-Bandung-Muar-Mi-...
3,4,Pau Mira Frozen Food Pagoh,Pau Mira Frozen Food is a Malaysian brand offe...,"food, culinary, frozen food",Food & Culinary,"KM13, Jalan Pagoh, 84600 Pagoh, Johor",Johor,9.2,15.0,8 am - 6 pm,Daily,Friday,4.6,HO3,Pau Mira,012-743 4086,https://www.facebook.com/paugebulembut/
4,5,Galeri Terompah Mastor,Galeri Terompah Mastor specializes in handcraf...,"footwear, crafts, wooden",Arts & Crafts,"Kg. Parit Hassan, Simpang Renggam, Kluang, Johor",Johor,98.0,600.0,8.30 am - 5.30 pm,Daily,Saturday,4.0,HO4,Galeri Terompah Mastor,6018-7649193,https://www.facebook.com/tourismjohor/posts/ga...

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226 entries, 0 to 225
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   item_id          226 non-null    int64
 1   title            226 non-null    object
 2   description      226 non-null    object
 3   tags             226 non-null    object
 4   category         226 non-null    object
 5   location         226 non-null    object
 6   state            226 non-null    object
 7   min price (RM)   226 non-null    float64
 8   max price (RM)   226 non-null    float64
 9   operating hours  226 non-null    object
 10  operating days   226 non-null    object
 11  closing days     76 non-null     object
 12  rating           225 non-null    float64
 13  host_id          226 non-null    object
 14  host_name        223 non-null    object
 15  contact          206 non-null    object
 16  more_info        216 non-null    object
dtypes: float64(3), int64(1), object(13)
memory usage: 30.1+ KB

In [45]:
#missing values
print ("\nMissing values per column:")
print(df.isna().sum())

#duplicate rows
print("\nNumber of duplicate rows:", df.duplicated().sum())

# Preview a few random rows
df.sample(5)

Missing values per column:
item_id              0
title                0
description          0
tags                 0
category             0
location             0
state                0
min price (RM)       0
max price (RM)       0
operating hours      0
operating days       0
closing days       150
rating               1
host_id              0
host_name            3
contact             20
more_info           10
dtype: int64

Number of duplicate rows: 0

,item_id,title,description,tags,category,location,state,min price (RM),max price (RM),operating hours,operating days,closing days,rating,host_id,host_name,contact,more_info
66,68,Herbal Nasuha,Malaysia’s largest herbal plantation with rest...,"herbs, agro tourism, wellness",Nature & Eco,"Jalan Muar, 84500 Muar, Johor Darul Ta'zim",Johor,1.0,20.0,10.30 a;m - 5.00 PM,Daily,NaN,4.2,HO65,Nasuha Herbs,018-768 1000,https://www.facebook.com/NasuhaHerbsRestaurant/
32,34,Pusat Pengembangan Tenun Pahang Diraja Kg. Soi,A cultural center showcasing Royal Pahang Weav...,"tenunpahang, weaving, heritage",Arts & Crafts,"Kampung Soi, Kuantan",Pahang,80.0,800.0,9 AM – 5 PM,Daily,Sunday,4.8,HO31,Pusat Tenun Diraja,-5161841,—
95,97,Sabahan Local Food Cooking Class at Kinarut,Learn to cook authentic Sabahan dishes with lo...,localfood cookingclass sabahan,Food & Culinary,Kinarut,Sabah,0.0,325.0,9 AM – 3 PM,Monday - Friday,"Saturday , Sunday",4.9,HO94,Kinabalu Culinary,NaN,Klook Page
4,5,Galeri Terompah Mastor,Galeri Terompah Mastor specializes in handcraf...,"footwear, crafts, wooden",Arts & Crafts,"Kg. Parit Hassan, Simpang Renggam, Kluang, Johor",Johor,98.0,600.0,8.30 am - 5.30 pm,Daily,Saturday,4.0,HO4,Galeri Terompah Mastor,6018-7649193,https://www.facebook.com/tourismjohor/posts/ga...
129,131,Cencol Sagu Rumbia,"Homemade dessert made from sago palm, a local ...","dessert, traditional, sago, borneo",Food & Culinary,Seremban,Negeri Sembilan,15.0,35.0,10:00 AM – 6:00 PM,Daily,NaN,4.7,HO128,Cencol Sagu Rumbia,011-2345 8765,https://www.facebook.com/cencolsagurumbia

In [49]:
df['closing days'].fillna('None', inplace=True)

In [55]:
df['rating'].fillna(df['rating'].median(), inplace=True)

C:\Users\Asus\AppData\Local\Temp\ipykernel_5136\333645285.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['rating'].fillna(df['rating'].median(), inplace=True)

In [57]:
df['host_name'].fillna('Unknown Host', inplace=True)

C:\Users\Asus\AppData\Local\Temp\ipykernel_5136\3031722755.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['host_name'].fillna('Unknown Host', inplace=True)

In [59]:
df['contact'].fillna('Not Provided', inplace=True)
df['more_info'].fillna('Not Available', inplace=True)

C:\Users\Asus\AppData\Local\Temp\ipykernel_5136\1685748828.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['contact'].fillna('Not Provided', inplace=True)
C:\Users\Asus\AppData\Local\Temp\ipykernel_5136\1685748828.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['more_info'].fillna('Not Available', inplace=True)

In [61]:
df.isnull().sum()

item_id            0
title              0
description        0
tags               0
category           0
location           0
state              0
min price (RM)     0
max price (RM)     0
operating hours    0
operating days     0
closing days       0
rating             0
host_id            0
host_name          0
contact            0
more_info          0
dtype: int64

In [63]:
df.dtypes

item_id              int64
title               object
description         object
tags                object
category            object
location            object
state               object
min price (RM)     float64
max price (RM)     float64
operating hours     object
operating days      object
closing days        object
rating             float64
host_id             object
host_name           object
contact             object
more_info           object
dtype: object

In [67]:
#data consistency
text_columns = [
    'title', 'description', 'tags', 'category', 'location',
    'state', 'operating hours', 'operating days', 'closing days',
    'host_name', 'contact', 'more_info'
]

# Clean each column
for col in text_columns:
    df[col] = (
        df[col]
        .astype(str)                              # Ensure it's string
        .str.strip()                              # Remove leading/trailing spaces
        .str.replace(r'\s+', ' ', regex=True)     # Replace multiple spaces
        .str.replace(r'[\n\t\r]', ' ', regex=True)# Remove line breaks/tabs
    )

# Standardize casing for some key columns
df['category'] = df['category'].str.title()
df['state'] = df['state'].str.title()
df['title'] = df['title'].str.title()

print("✅ Text data cleaned and standardized!")
df.head(3)

✅ Text data cleaned and standardized!

,item_id,title,description,tags,category,location,state,min price (RM),max price (RM),operating hours,operating days,closing days,rating,host_id,host_name,contact,more_info
0,1,Ilham Ceramic Studio,"Ilham Seramik Studio showcases ceramic-making,...","ceramic, crafts, pottery",Arts & Crafts,"Ilham Ceramic Studio, Kampung Bendang Baru, 07...",Kedah,8.0,518.0,9 am - 5 pm,Daily,Friday,4.8,HO1,Radzi Ismail,013-599 4022,https://www.instagram.com/ilham_ceramic/?hl=en
1,2,Maklang Cafe By Ilham Ceramic Studio,Maklang Cafe by Ilham Ceramic offers cultural ...,"food, culture, culinary",Food & Culinary,"Ilham Ceramic Studio, Kampung Bendang Baru, 07...",Kedah,0.5,15.0,8 am - 6 pm,Daily,Friday,4.8,HO1,Radzi Ismail,013-599 4022,https://naturallylangkawi.my/portfolio/ilham-s...
2,3,Perencah Mee Bandung Mak Pon,Perencah Mee Bandung Mak Pon offers varieties ...,"food, paste, culinary",Food & Culinary,"1, 2 & 3, Jalan Lembah Padang, Taman Lembah Pa...",Johor,12.0,30.0,10 am - 7 pm,Daily,None,4.0,HO2,JJ Makpon Muar,012-262 0044,https://shopee.com.my/Pes-Mee-Bandung-Muar-Mi-...

In [73]:
def fix_time_seconds(text):
    if pd.isna(text):
        return text
    text = str(text)

    # Only touch text that contains AM/PM (ignore "Upon Booking", etc.)
    if re.search(r'\bAM\b|\bPM\b', text):
        # Remove any double :00 like 8:30:00:00 → 8:30
        text = re.sub(r'(\d{1,2}:\d{2})(:00)+', r'\1', text)

        # Remove :00 for whole hours like 8:00 → 8:00 (keep one only)
        text = re.sub(r'(\d{1,2}):00(?=\s*[AP]M)', r'\1:00', text)

        # Fix any trailing extra colons accidentally formed
        text = re.sub(r':+', ':', text)

    return text

df['operating hours'] = df['operating hours'].apply(fix_time_seconds)

print("✅ Seconds removed and time formats perfected!")
df['operating hours'].head(10)

✅ Seconds removed and time formats perfected!

0     9:00 AM – 5:00 PM
1     8:00 AM – 6:00 PM
2    10:00 AM – 7:00 PM
3     8:00 AM – 6:00 PM
4     8:30 AM – 5:30 PM
5    11:00 AM – 8:00 PM
6          Upon Booking
7     9:00 AM – 6:00 PM
8      Temporary Closed
9     9:00 AM – 6:00 PM
Name: operating hours, dtype: object

In [75]:
import re
import numpy as np

# Function to extract opening and closing times
def split_hours(value):
    if isinstance(value, str):
        # Handle special text cases
        if "upon" in value.lower() or "temporary" in value.lower() or "closed" in value.lower():
            return pd.Series([np.nan, np.nan])
        
        # Match "9:00 AM – 5:00 PM" pattern
        match = re.match(r"(\d{1,2}:\d{2}(?::\d{2})?\s?(?:AM|PM))\s*[–-]\s*(\d{1,2}:\d{2}(?::\d{2})?\s?(?:AM|PM))", value, re.IGNORECASE)
        if match:
            return pd.Series(match.groups())
    
    return pd.Series([np.nan, np.nan])

# Apply function to your column
df[['opening_time', 'closing_time']] = df['operating hours'].apply(split_hours)

# Drop seconds from the new columns for a cleaner look
df['opening_time'] = df['opening_time'].str.replace(r":00\s", " ", regex=True)
df['closing_time'] = df['closing_time'].str.replace(r":00\s", " ", regex=True)

# Display sample
df[['operating hours', 'opening_time', 'closing_time']].head(10)

      operating hours opening_time closing_time
0   9:00 AM – 5:00 PM         9 AM         5 PM
1   8:00 AM – 6:00 PM         8 AM         6 PM
2  10:00 AM – 7:00 PM        10 AM         7 PM
3   8:00 AM – 6:00 PM         8 AM         6 PM
4   8:30 AM – 5:30 PM      8:30 AM      5:30 PM
5  11:00 AM – 8:00 PM        11 AM         8 PM
6        Upon Booking          NaN          NaN
7   9:00 AM – 6:00 PM         9 AM         6 PM
8    Temporary Closed          NaN          NaN
9   9:00 AM – 6:00 PM         9 AM         6 PM

In [79]:
# Show unique examples of each column
print("Unique operating days:")
print(df['operating days'].unique()[:30])  # only show first 30 for now

print("\nUnique closing days:")
print(df['closing days'].unique()[:30])

Unique operating days:
['Daily' 'Upon Booking' 'Temporary Closed' 'Seasonally'
 'Daily by appointment' '18 -19 October' 'Saturday' 'Mon–Sat'
 'Monday - Friday' 'Mon – Sat' 'Tue – Sun' 'Saturday, Sunday'
 'Monday – Saturday' 'Annually' 'Annual Event' 'Mon – Fri' 'Mon-Sat'
 'Friday, Saturday']

Unique closing days:
['Friday' 'None' 'Saturday' 'Upon Booking' 'Temporary Closed' 'Seasonally'
 'Sunday' 'Saturday, Sunday' 'Tuesday, friday' 'Tuesday' 'Monday, Tuesday'
 'Wednesday' 'Thursday' 'Saturday , Sunday' 'Monday' 'Monday - Friday'
 'Weekend' 'Fri' 'Friday, Saturday' 'Sunday - Thursday' 'Sunday - Friday']

In [83]:
import re

# Helper function to standardize days
def clean_days(text):
    if pd.isna(text) or text.strip() == "" or text.lower() == "none":
        return "Not Mentioned"
    
    text = text.strip().lower()
    
    # Handle special terms
    if "daily" in text or "everyday" in text:
        return "Daily"
    if "upon booking" in text:
        return "Upon Booking"
    if "temporary" in text:
        return "Temporary Closed"
    if "season" in text:
        return "Seasonal"
    if "annual" in text:
        return "Annual Event"
    
    # Replace symbols and normalize
    text = text.replace("–", "-").replace(",", " ").replace(";", " ")
    text = re.sub(r"\s+", " ", text).strip()
    
    # Map short forms to full names
    replacements = {
        "mon": "Monday", "tue": "Tuesday", "wed": "Wednesday",
        "thu": "Thursday", "fri": "Friday", "sat": "Saturday", "sun": "Sunday"
    }
    
    for short, full in replacements.items():
        text = re.sub(rf"\b{short}\b", full, text)
    
    # Normalize ranges (e.g., Monday - Friday)
    text = text.title()
    text = text.replace(" - ", " – ")
    
    return text

# Apply cleaning
df['operating days'] = df['operating days'].apply(clean_days)
df['closing days'] = df['closing days'].apply(clean_days)

# Preview result
df[['operating days', 'closing days']].head(15)

      operating days      closing days
0              Daily            Friday
1              Daily            Friday
2              Daily               N/A
3              Daily            Friday
4              Daily          Saturday
5              Daily               N/A
6       Upon Booking      Upon Booking
7              Daily               N/A
8   Temporary Closed  Temporary Closed
9           Seasonal          Seasonal
10             Daily      Upon Booking
11             Daily               N/A
12  Temporary Closed  Temporary Closed
13      Upon Booking      Upon Booking
14      Upon Booking      Upon Booking

In [89]:
df['operating days'].replace("N/A", "Not mentioned", inplace=True)
df['closing days'].replace("N/A", "Not mentioned", inplace=True)
df[['operating days', 'closing days']].head()

C:\Users\Asus\AppData\Local\Temp\ipykernel_5136\904292681.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['operating days'].replace("N/A", "Not mentioned", inplace=True)
C:\Users\Asus\AppData\Local\Temp\ipykernel_5136\904292681.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['closing days'].replace("N/A", "Not mentioned", inplace=True)

  operating days   closing days
0          Daily         Friday
1          Daily         Friday
2          Daily  Not mentioned
3          Daily         Friday
4          Daily       Saturday

In [91]:
import re

# Define mapping for short forms
day_map = {
    "Mon": "Monday",
    "Tue": "Tuesday",
    "Wed": "Wednesday",
    "Thu": "Thursday",
    "Thur": "Thursday",
    "Fri": "Friday",
    "Sat": "Saturday",
    "Sun": "Sunday"
}

In [93]:
def standardize_days(text):
    if pd.isna(text) or text.strip().lower() in ['none', 'not mentioned', 'n/a']:
        return "Not mentioned"
    
    text = text.strip()

    # Handle special cases
    lower_text = text.lower()
    if "upon booking" in lower_text:
        return "Upon Booking"
    if "temporary closed" in lower_text or "season" in lower_text:
        return "Temporarily Closed"
    if "annual" in lower_text or "festival" in lower_text:
        return "Annual Event"

    # Replace short day names with full names
    for short, full in day_map.items():
        text = re.sub(rf"\b{short}\b", full, text, flags=re.IGNORECASE)
    
    # Replace common separators with a consistent " – "
    text = re.sub(r"[-–,]", " – ", text)
    text = re.sub(r"\s+", " ", text).strip()  # remove double spaces

    return text

In [95]:
df['operating days'] = df['operating days'].apply(standardize_days)
df['closing days'] = df['closing days'].apply(standardize_days)

In [97]:
print("✅ Unique operating days after cleaning:")
print(df['operating days'].unique())

print("\n✅ Unique closing days after cleaning:")
print(df['closing days'].unique())

✅ Unique operating days after cleaning:
['Daily' 'Upon Booking' 'Temporarily Closed' '18 – 19 October' 'Saturday'
 'Monday – Saturday' 'Monday – Friday' 'Tuesday – Sunday'
 'Saturday Sunday' 'Annual Event' 'Friday Saturday']

✅ Unique closing days after cleaning:
['Friday' 'Not mentioned' 'Saturday' 'Upon Booking' 'Temporarily Closed'
 'Sunday' 'Saturday Sunday' 'Tuesday Friday' 'Tuesday' 'Monday Tuesday'
 'Wednesday' 'Thursday' 'Monday' 'Monday – Friday' 'Weekend'
 'Friday Saturday' 'Sunday – Thursday' 'Sunday – Friday']

In [99]:
def final_day_cleanup(text):
    if pd.isna(text) or text.lower() in ['not mentioned', 'n/a']:
        return "Not mentioned"

    text = text.strip()

    # Normalize general terms
    replacements = {
        "Weekend": "Saturday – Sunday",
        "Weekends": "Saturday – Sunday",
        "Weekdays": "Monday – Friday",
        "Daily": "Daily",
        "Annual Event": "Annual Event",
        "Temporarily Closed": "Temporarily Closed",
        "Upon Booking": "Upon Booking"
    }
    for old, new in replacements.items():
        if old.lower() in text.lower():
            return new

    # Fix day pair formats (e.g. "Saturday Sunday" -> "Saturday – Sunday")
    text = re.sub(r"(?<=Saturday)\s+(?=Sunday)", " – ", text, flags=re.IGNORECASE)
    text = re.sub(r"(?<=Friday)\s+(?=Saturday)", " – ", text, flags=re.IGNORECASE)
    text = re.sub(r"(?<=Tuesday)\s+(?=Friday)", " – ", text, flags=re.IGNORECASE)
    text = re.sub(r"(?<=Monday)\s+(?=Tuesday)", " – ", text, flags=re.IGNORECASE)

    # Remove duplicate spaces and ensure consistent separator
    text = re.sub(r"\s*[-–]\s*", " – ", text)
    text = re.sub(r"\s+", " ", text).strip()

    return text

# Apply to both columns
df['operating days'] = df['operating days'].apply(final_day_cleanup)
df['closing days'] = df['closing days'].apply(final_day_cleanup)

In [101]:
print("✅ Unique operating days (final):")
print(df['operating days'].unique())

print("\n✅ Unique closing days (final):")
print(df['closing days'].unique())

✅ Unique operating days (final):
['Daily' 'Upon Booking' 'Temporarily Closed' '18 – 19 October' 'Saturday'
 'Monday – Saturday' 'Monday – Friday' 'Tuesday – Sunday'
 'Saturday – Sunday' 'Annual Event' 'Friday – Saturday']

✅ Unique closing days (final):
['Friday' 'Not mentioned' 'Saturday' 'Upon Booking' 'Temporarily Closed'
 'Sunday' 'Saturday – Sunday' 'Tuesday – Friday' 'Tuesday'
 'Monday – Tuesday' 'Wednesday' 'Thursday' 'Monday' 'Monday – Friday'
 'Friday – Saturday' 'Sunday – Thursday' 'Sunday – Friday']

In [103]:
# Step 1: Find rows where min price > max price
invalid_prices = df[df['min price (RM)'] > df['max price (RM)']]
print("⚠️ Invalid price ranges detected:")
display(invalid_prices)

# Step 2: Fix cases where min > max (swap them)
df.loc[df['min price (RM)'] > df['max price (RM)'], ['min price (RM)', 'max price (RM)']] = \
    df.loc[df['min price (RM)'] > df['max price (RM)'], ['max price (RM)', 'min price (RM)']].values

# Step 3: Identify zero or negative prices
invalid_zero = df[(df['min price (RM)'] <= 0) | (df['max price (RM)'] <= 0)]
print("⚠️ Zero or negative prices detected:")
display(invalid_zero)

⚠️ Invalid price ranges detected:

Empty DataFrame
Columns: [item_id, title, description, tags, category, location, state, min price (RM), max price (RM), operating hours, operating days, closing days, rating, host_id, host_name, contact, more_info, opening_time, closing_time]
Index: []

⚠️ Zero or negative prices detected:

,item_id,title,description,tags,category,location,state,min price (RM),max price (RM),operating hours,operating days,closing days,rating,host_id,host_name,contact,more_info,opening_time,closing_time
16,18,Songket Weaving Memento Experience,Tanoti artisans will assist participants to de...,"weaving, textile, arts",Arts & Crafts,"Tanoti House, Kuching, Sarawak",Sarawak,0.0,250.00,8:00 AM – 4:00 pm,Daily,Not mentioned,4.3,HO15,Tanoti,0 82 239 277,https://tanoticrafts.com/products/tanoti-songk...,8 AM,4 pm
25,27,Galeri Tekatan Benang Emas,Galeri Tekatan Benang Emas in Perak showcases ...,"embroidery, gold thread, craft, heritage, arts...",Arts & Crafts,"33000, 73, Kampung Padang Changkat, Bukit Chan...",Perak,0.0,3.00,10:00 AM – 5:00 PM,Daily,Sunday,5.0,HO24,Hajah Azizah,Not Provided,https://www.facebook.com/hajjahazizahyusof/?lo...,10 AM,5 PM
36,38,Kampung Budaya Terengganu,An open-air cultural village offering live dem...,"culturalvillage, terengganu, heritage",Culture & Heritage,"Terengganu State Museum, Kampung Bukit Losong,...",Terengganu,0.0,5.00,9:00 AM – 5:00 PM,Daily,Tuesday – Friday,4.7,HO35,Kampung Budaya Terengganu,09-623 1553,https://www.discoveryterengganu.com/tempat/kam...,9 AM,5 PM
40,42,Festival Wayang Wong 2025,A Javanese theater festival in Johor blending ...,"festival, performing arts, heritage",Festivals & Performances,"Keraton Mbah Anang, Muar Johor",Johor,0.0,0.00,8:00 PM – 11:00 PM,18 – 19 October,Not mentioned,3.8,HO39,Persatuan Jawa Parit Bugis Johor,013-679 3242,https://www.facebook.com/PJPBM/,8 PM,11 PM
58,60,Eco Tourism Kampung Sungai Melayu,Community-run eco-tourism business offering ma...,"ecotourism, mangrove, community-based",Nature & Eco,"eside Asam pedas (berdekatan klinik desa, Jala...",Johor,0.0,35.00,9:00 AM – 4:00 PM,Daily,Not mentioned,4.5,HO57,Koperasi Penduduk Kampung Sungai Melayu,011-6779 6693,https://www.facebook.com/people/Eco-Pelanconga...,9 AM,4 PM
60,62,Open Traditional Dance Class,Experience learning traditional Malaysian danc...,"traditional dance, culture, experience",Festivals & Performances,Dataran Tanjung Emas Muar,Johor,0.0,0.00,8:30 PM – 11:00 PM,Saturday,Not mentioned,4.3,HO59,Unknown Host,Not Provided,tiktok,8:30 PM,11 PM
69,71,Galeri Wau Pak Sapie And Sons,A local art and craft shop specializing in tra...,"wau, craft, heritage, culture",Arts & Crafts,"Galeri Wau Pak Sapie, Jalan Pantai Cahaya Bula...",Kelantan,0.0,20.00,9:00 AM – 3:00 PM,Daily,Not mentioned,4.3,HO68,Wan Anuar,0 13-395 4207,https://www.facebook.com/galeriwau/,9 AM,3 PM
74,76,Ikan Bilis Sabarang Sungai Enterprise,A local seafood supplier near Bebuluh Water Vi...,"seafood, local product, Labuan",Nature & Eco,"Bebuloh laut, Bl 0045A, Kampung Bebuloh Laut, ...",Labuan,0.0,0.00,8:00 AM – 5:00 PM,Daily,Friday,5.0,HO73,Unknown Host,012-8311849,Not Available,8 AM,5 PM
76,78,Traditional Nyonya Dessert Cooking Class In Me...,Learn to make authentic Peranakan desserts whi...,"nyonya, dessert, cooking class, heritage",Food & Culinary,"Jaya Mata Knife Gallery, 104 & 106, Jalan Toko...",Melaka,0.0,136.00,Upon Booking,Upon Booking,Upon Booking,4.6,HO75,Jaya Mata,Not Provided,https://www.klook.com/ms-MY/activity/85757-tra...,NaN,NaN
77,79,Batik Wau Bulan (A Malaysian Heritage Kite) Ma...,Hands-on batik and kite-making workshop teachi...,"wau bulan, batik, craft, workshop",Arts & Crafts,"55, Jalan Kampung Pantai, Kampung Pantai, 7520...",Melaka,0.0,50.00,11:00 AM – 8:00 PM,Daily,Not mentioned,4.6,HO76,Malacca Heritage Weekend Workshop,011-2177 6974,https://theweekendworkshop.com.my/malacca/prod...,11 AM,8 PM
88,90,Biking Through Malay Countryside,"Cycling tour through plantations, orchards, an...","cycling, countryside, eco tourism",Nature & Eco,George Town,Penang,0.0,130.00,7:00 AM – 10:15 AM,Upon Booking,Upon Booking,4.9,HO87,Eddie,Not Provided,https://www.airbnb.com/experiences/285231?loca...,7 AM,10:15 AM
95,97,Sabahan Local Food Cooking Class At Kinarut,Learn to cook authentic Sabahan dishes with lo...,localfood cookingclass sabahan,Food & Culinary,Kinarut,Sabah,0.0,325.00,9:00 AM – 3:00 PM,Monday – Friday,Saturday – Sunday,4.9,HO94,Kinabalu Culinary,Not Provided,Klook Page,9 AM,3 PM
109,111,Learn Authentic Malaysian Vegan Cooking,Hands-on vegan cooking class showcasing Malays...,"cooking class, vegan, malaysia, food",Food & Culinary,Petaling Jaya,Selangor,0.0,220.00,11:00 AM – 1:15 PM,Daily,Not mentioned,4.9,HO108,Zurana,Not Provided,https://www.airbnb.com/experiences/474742?loca...,11 AM,1:15 PM
112,114,Explore The Origin Of Kuala Lumpur With A Local,"Walking tour through KL’s historical sites, ex...","kuala lumpur, walking tour, history, culture",Culture & Heritage,Kuala Lumpur,Kuala Lumpur,0.0,70.00,5:00 PM – 7:30 PM,Daily,Not mentioned,4.9,HO111,Efmike,Not Provided,https://www.airbnb.com/experiences/283497,5 PM,7:30 PM
113,115,Explore Kampung Baru With A Local,Discover Kampung Baru’s culture and cuisine wi...,"kampung baru, heritage, tour, food",Culture & Heritage,Kuala Lumpur,Kuala Lumpur,0.0,155.00,5:00 PM – 8:00 PM,Daily,Not mentioned,4.9,HO112,Fuad,Not Provided,https://www.airbnb.com/experiences/157841,5 PM,8 PM
115,117,Malaysian Batik Experience – Handkerchief,Short batik workshop where visitors color and ...,"batik, workshop, art, souvenir",Arts & Crafts,Kuala Lumpur,Kuala Lumpur,0.0,73.53,10:00 AM – 2:00 PM,Daily,Not mentioned,5.0,HO114,Batik Workshop KL,Not Provided,https://www.tripadvisor.com.my/AttractionProdu...,10 AM,2 PM
116,118,Step Into Batu Caves,Guided cultural and religious experience throu...,"batu caves, culture, tour, heritage",Culture & Heritage,Kuala Lumpur,Kuala Lumpur,0.0,190.00,8:00 AM – 4:00 PM,Daily,Not mentioned,5.0,HO115,Eddy,Not Provided,https://www.airbnb.com/experiences/4458059,8 AM,4 PM
120,122,Take A Guided Ride On The Wind And Green Malacca,Eco-friendly cycling tour through Malacca’s co...,"cycling tour, eco, malacca, outdoor",Nature & Eco,Ayer Salak,Melaka,0.0,218.00,7:00 AM – 11:00 PM,Daily,Not mentioned,4.9,HO119,Joseph,-,https://www.airbnb.ie/experiences/1793557,7 AM,11 PM
121,123,Unesco Heritage Discovery Ride,Explore Malacca’s UNESCO World Heritage sites ...,"heritage, tour, malacca, unesco",Culture & Heritage,Malacca,Melaka,0.0,218.00,8:30 AM – 12:00 PM,Saturday – Sunday,Monday – Friday,5.0,HO120,Joseph,-,https://www.airbnb.com/experiences/3396554,8:30 AM,12 PM
125,127,Historical Malacca Day Tour From Kuala Lumpur ...,Full-day private guided tour exploring Malacca...,"malacca, tour, heritage, history",Culture & Heritage,Jonker Walk,Melaka,0.0,378.46,8:00 AM – 6:00 PM,Daily,Not mentioned,4.8,HO124,Private Malacca Historical tour,-,https://www.tripadvisor.com.my/AttractionProdu...,8 AM,6 PM
147,149,Choley Kampung Warna Warni Kuala Perlis,Colorful village attraction with vibrant mural...,"village, tourism, perlis, culture",Nature & Eco,Kuala Perlis,Perlis,0.0,0.00,8:00 AM – 7:00 PM,Daily,Not mentioned,4.8,HO146,Kampung Warna Warni,011-909 2299,https://www.facebook.com/KampungWarnaWarni,8 AM,7 PM
159,161,Malaysia Games Festival @ Putrajaya 2025 (Fpm@...,"Annual festival celebrating Malaysian games, f...","festival, games, culture, putrajaya",Festivals & Performances,Putrajaya,Putrajaya,0.0,0.00,10:00 AM – 10:00 PM,Annual Event,Not mentioned,4.9,HO158,Malaysia Games Fest,03-8888 8888,https://www.facebook.com/MalaysiaGamesFestival,10 AM,10 PM
161,163,Festival Lentera Putrajaya,Lantern-themed festival featuring light displa...,"festival, lantern, night event, putrajaya",Festivals & Performances,Putrajaya,Putrajaya,0.0,10.00,7:00 PM – 11:00 PM,Annual Event,Not mentioned,4.9,HO160,Lentera Festival Team,011-1200 3345,https://www.facebook.com/FestivalLenteraPutrajaya,7 PM,11 PM
186,188,Khairol Fiber Group,A boat and fiberglass craft manufacturer based...,"boatmaking, craftsmanship, marine, terengganu",Arts & Crafts,"Lot 8126, Jalan Kuala Abang, Kg Bukit Pauh, 23...",Terengganu,0.0,0.00,9:00 AM – 5:30 PM,Monday – Saturday,Sunday,4.9,HO185,Khairol Fiber Group,010-252 6129,https://khairolfibergroup.com khairolfibergrou...,9 AM,5:30 PM
198,200,Botanical Gardens Penang,A lush tropical park established in 1884 with ...,"nature, garden, eco, penang",Nature & Eco,George Town,Penang,0.0,0.00,5:00 AM – 8:00 PM,Daily,Not mentioned,4.5,HO197,Botanical Gardens Penang,014-555 1234,Free entry; official page: botanicalgardens.pe...,5 AM,8 PM
199,201,Chew Jetty,A historic con­struction of stilt houses belon...,"heritage, culture, waterfront, penang",Culture & Heritage,George Town,Penang,0.0,0.00,9:00 AM – 6:00 PM,Daily,Not mentioned,4.4,HO198,Chew Jetty Community,016-222 3344,Visit the wooden boardwalk for sunset views.,9 AM,6 PM
206,208,Penang Street Art,Iconic murals and installations across George ...,"art, heritage, mural, penang",Arts & Crafts,George Town,Penang,0.0,0.00,24 Hours,Daily,Not mentioned,4.9,HO205,Penang Street Art Walk,017-556 7766,Free to view; self-guided.,NaN,NaN
214,216,Kampung Laut Cultural Heritage Site,Historical and cultural site featuring traditi...,"heritage, culture, architecture, kelantan",Culture & Heritage,Wakaf Bharu,Kelantan,0.0,1.00,8:00 AM – 5:00 PM,Daily,Friday – Saturday,4.7,HO213,Laman Warisan Kampung Laut,Not Provided,https://www.facebook.com/kampunglautkelantan/,8 AM,5 PM
222,224,Langkawi Eco Ventures (Mangrove Kayak Tour),Guided kayak tours through Langkawi’s mangrove...,"eco tour, mangrove, kayaking, langkawi",Nature & Eco,Langkawi,Kedah,0.0,278.00,24 hours,Daily,Friday,5.0,HO221,Langkawi Eco Ventures,011-2414 6766,https://www.langkawiecoventures.com/,NaN,NaN
223,225,Kampung Padi,A peaceful village stay surrounded by rice fie...,"homestay, culture, paddy, kedah",Culture & Heritage,Sungai Petani,Kedah,0.0,0.00,9:00 AM – 11:00 PM,Daily,Tuesday,4.1,HO222,Kampung Padi,017-563 6056,https://www.facebook.com/tourismkedah/posts/ke...,9 AM,11 PM

In [105]:
def classify_price(row):
    if row['min price (RM)'] == 0 or row['max price (RM)'] == 0:
        return "Free / Not mentioned"
    elif row['min price (RM)'] < 0 or row['max price (RM)'] < 0:
        return "Invalid"
    else:
        return "Paid"

df['price_type'] = df.apply(classify_price, axis=1)

In [107]:
invalid_prices = df[df['price_type'] == "Invalid"]
print(f"⚠️ Invalid price entries: {len(invalid_prices)}")

⚠️ Invalid price entries: 0

In [109]:
df['price_type'].value_counts()

price_type
Paid                    196
Free / Not mentioned     30
Name: count, dtype: int64

In [111]:
df.dtypes

item_id              int64
title               object
description         object
tags                object
category            object
location            object
state               object
min price (RM)     float64
max price (RM)     float64
operating hours     object
operating days      object
closing days        object
rating             float64
host_id             object
host_name           object
contact             object
more_info           object
opening_time        object
closing_time        object
price_type          object
dtype: object

In [113]:
invalid_price_order = df[df['min price (RM)'] > df['max price (RM)']]
invalid_ratings = df[(df['rating'] < 0) | (df['rating'] > 5)]

In [117]:
df.to_csv('cleaned_dataset.csv', index=False)